### ISSUE TITLE
Merge tables throws error on column type matching

### ISSUE THREAD

**Issue by mtdukes** [onyxfish/agate#448] opened 2016-02-01 19:11 UTC
Trying to merge two tables with identical column types, per the documentation, and getting the "Only tables with identical column types may be merged" error

Printing the column_types for both tables shows:

|---------------+---------------|
|  column_names | column_types  |
|---------------+---------------|
|  sponsor      | Text          |
|  amount       | Number        |
|  detail       | Text          |
|  change_type  | Text          |
|---------------+---------------|
|---------------+---------------|
|  column_names | column_types  |
|---------------+---------------|
|  sponsor      | Text          |
|  amount       | Number        |
|  detail       | Text          |
|  change_type  | Text          |
|---------------+---------------|

Maybe this is an error in the code?

**Comment by nbedi** [comment] 2016-02-01 19:27
Looks like a possible duplicate of #435. Could you try your script on the master branch and see if that works?

**Comment by onyxfish** [comment] 2016-02-05 13:32
Agree that this is probably already fixed. Marking low until we hear back.

**Comment by onyxfish** [comment] 2016-02-05 22:50
I'm going to go ahead and close this out since the limitation was removed in `1.2.2` anyway. Please reopen if you spot the issue again.

**Closed by onyxfish** 2016-02-05 22:50 UTC
Labels: bug, priority-low
